version: "3.8"

services:
  postgres:
    image: rnsrk/postgres:alpine
    build: 
        context: ./postgres_context
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data:rw

  drupal:
      image: rnsrk/drupal:10.0.9-php8.2-fpm-alpine
      build: 
        context: ./drupal_context
      container_name: drupal
      depends_on:
        - postgres
      restart: unless-stopped
      volumes:
        - ./volumes/drupal/data:/opt/drupal:rw
        - ./volumes/drupal/private_files:/var/www/private_files

  solr:
      image: solr:8-slim
      container_name: solr
      restart: unless-stopped
      volumes:
        - solr-data:/opt/solr
      environment:
        SOLR_JAVA_MEM: "-Xms256M -Xmx512M"

  graphdb:
    image: rnsrk/graphdb
    container_name: graphdb
    restart: unless-stopped
    build: 
      context: ./graphdb_context
    volumes:
      - graphdb_data:/graphdb/data

  adminer:
    image: adminer:fastcgi
    container_name: adminer
    restart: unless-stopped

  webserver:
      image: nginx:1.23-alpine
      container_name: webserver
      depends_on:
        - drupal
        - solr
        - graphdb
        - adminer
      restart: unless-stopped
      ports:
        - 80:80
      volumes:
        - ./volumes/drupal/data:/opt/drupal
        - ./nginx_context/server_conf:/etc/nginx/conf.d/
        - ./nginx_context/.htpasswd:/usr/share/nginx/.htpasswd

volumes:
  graphdb_data:
  solr-data:
