version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: dlza_postgresql
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  drupal:
      image: rnsrk/drupal:9.4.7-fpm-alpine-extended
      build: 
        context: ./drupal_context
      container_name: dlza_drupal
      depends_on:
        - postgres
      restart: unless-stopped
      volumes:
        - drupal-data:/opt/drupal
        - ./drupal_context/custom-php-settings.ini:/usr/local/etc/php/conf.d/99-custom-settings.ini

  webserver:
      image: nginx:1.23-alpine
      container_name: dlza_webserver
      depends_on:
        - drupal
      restart: unless-stopped
      ports:
        - 3001:80
      volumes:
        - drupal-data:/opt/drupal
        - ./nginx-conf:/etc/nginx/conf.d

  solr:
      image: solr:8-slim
      container_name: dlza_solr
      restart: unless-stopped
      volumes:
        - solr-data:/opt/solr
      environment:
        SOLR_JAVA_MEM: "-Xms256M -Xmx512M"

  graphdb:
    image: rnsrk/graphdb:10.0.2
    container_name: dlza_graphdb
    restart: unless-stopped
    build: 
      context: ./graphdb_context
    volumes:
      - graphdb-data:/graphdb/data

  adminer:
    image: adminer:fastcgi
    container_name: dlza_adminer
    restart: unless-stopped

volumes:
  db-data:
  drupal-data:
    driver_opts:
           type: none
           device: ${DRUPAL_DATA} #NOTE needs full path (~ or ./ doesn't work)
           o: bind
  graphdb-data:
  solr-data:
